language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

addons:
  hosts:
    - localhost
  hostname: localhost

after_success:
- ./gradlew jacocoTestReport
  - bash <(curl -s https://codecov.io/bash)
